# Training Configuration for Wall-X Robotic Multi-Modal Learning
# This configuration supports multi-modal learning with vision, language, and action data

# Model and paths configuration
log_name: "libero-bus2507_plus_moe"
log_project: "github_benchmark"
model_type: qwen2_5

use_fast_tokenizer: false
pretrained_wallx_path: "/x2robot_v2/Models/Qwen2.5-VL-3B-Instruct"
## 从model config中选模型
qwen_vl_act_config_path: "/x2robot_v2/yangping/github/wall-x/workspace/model_config/moe_flash.json"

resume:
  ckpt: /x2robot_v2/share/bus0701/move_ckpts/bus_0717/flow_unfreeze/epoch0/0
  try_harder: true

seed: 10233
# seed: 10234

model_type: qwen2_5
processor_path: "/x2robot_v2/Models/Qwen2.5-VL-3B-Instruct"
pretrained_qwen_vl_path: "/x2robot_v2/Models/Qwen2.5-VL-3B-Instruct"  ## 以vlm的形式加载fast的模型


save_path: "/x2robot_v2/share/yangping/ckpt/robochallenge_github/benchmark/libero/bus2507_plus_moe-0125"

# Torch Profile
profile: False
profile_save_path: ./profile/
profile_wait_iters: 10
profile_warmup_iters: 5
profile_active_iters: 2

# Training hyperparameters
num_warmup_steps: 1000
num_training_steps: 64000000
learning_rate: 0.0001
min_lr: 0.00005
num_epoch: 64
gradient_accumulation_steps: 8
batch_size_per_gpu: 8
padding_side: left
epoch_save_interval: 1

# Robot configuration - Define degrees of freedom for each component
dof_config:
  master_right_ee_cartesian_pos: 3     # Right end-effector Cartesian position
  master_right_ee_rotation: 3          # Right end-effector rotation
  master_right_gripper: 1              # Right gripper control

# Agent proprioception configuration (typically matches DOF config)
agent_pos_config:
  follow_right_ee_cartesian_pos: 3
  follow_right_ee_rotation: 3
  follow_right_gripper: 1

# norm_stats_path: "/x2robot_v2/yangping/github/norm/benchmark/libero/norm_stats.json"
norm_stats_path: "/mnt/data/x2robot_v2/yangping/data/benchmark/libero/stats/stats.json"
# customized_action_statistic_dof: "customized_action_statistic_dof"


enable_customized_robot_config: true
customized_robot_config:
  name: "libero"
  customized_dof_config:
    "action_all" : 7 #To match the total number of degrees of freedom

  customized_agent_pos_config:
    "state_all" : 7 #To match the total number of degrees of freedom


# Data configuration

FSDP2: False
torch_compile: False

data:
  use_lerobot: true

  # LeRobot dataset configuration
  lerobot_config:
    repo_id: "libero"
    root: "/x2robot_v2/share/yangping/data/lerobot/benchmark/libero_all"
    episodes: null
    image_transforms: null
    delta_timestamps: null
    tolerance_s: 1e-4
    revision: null
    force_cache_sync: false
    download_videos: true
    video_backend: null

  action_horizon: 10
  train_test_split: 0.95

  # Action keys for observation and prediction
  obs_action_keys:
    - follow_right_ee_cartesian_pos
    - follow_right_ee_rotation
    - follow_right_gripper

  predict_action_keys:
    - master_right_ee_cartesian_pos
    - master_right_ee_rotation
    - master_right_gripper

  # Image resolution configuration for different camera views
  instruction_path: ['/x2robot_v2/share/xzn/datasets/x2robot/libero_20251016/libero_all/instruction.json']
  resolution:
    face_view: 256
    left_wrist_view: 256
    right_wrist_view: 256
    move1_view: 256
    move2_view: 256
    top_view: 256
    wall_view: 256
    multi_modal: 256
